"""Exercise `cathedral_measurement_approval.py approve` -- the recovery path.

Every other subcommand of this tool is covered (`renew`, `rollover`,
`republish-install`, `install-candidate`). `approve` was not, and it is the one
a provider actually needs: the launch measurement folds in all four RTMRs, so
any initramfs regeneration moves it and the machine stops being admitted until
someone runs this (cathedral-compute#88).

That left the recovery path in the worst possible state -- reasoned about,
documented, and never executed. A recovery path first exercised during an
outage is a recovery path with unknown failure modes.

`_capture` is the seam: it talks to a live worker through the pinned production
verifier, which no test can do. Everything AFTER it -- release bump, signing,
self-verification, the approval record, and the rollback when the record cannot
be written -- is the part that has to work under pressure, and is what these
drive.
"""
from __future__ import annotations

import base64
import importlib.util
import json
from pathlib import Path

import pytest
from cathedral.policy_registry import PolicyRegistryState, verify_registry
from tests.test_registry_reissue import REGISTRY_BYTES, REGISTRY_SEED, TRUSTED

_SPEC = importlib.util.spec_from_file_location(
    "cathedral_measurement_approval_recovery",
    Path(__file__).resolve().parents[1] / "scripts" / "cathedral_measurement_approval.py",
)
approval = importlib.util.module_from_spec(_SPEC)
assert _SPEC.loader is not None
_SPEC.loader.exec_module(approval)

# What a machine looks like after `apt full-upgrade` regenerated its initramfs:
# a well-formed measurement that is simply not the approved one.
DRIFTED = "tdx-measurement-sha256:" + "d1" * 32


def _candidate(measurement: str = DRIFTED) -> dict:
    return {
        "measurement": measurement,
        "tcb_status": "UpToDate",
        "chip_id": "tdx-platform-sha256:" + "c" * 64,
    }


def _inputs(tmp_path: Path):
    registry = tmp_path / "registry.json"
    registry.write_bytes(REGISTRY_BYTES)
    registry.chmod(0o644)
    key = tmp_path / "policy-signing.key"
    key.write_text(base64.b64encode(REGISTRY_SEED).decode("ascii"))
    key.chmod(0o600)
    PolicyRegistryState(tmp_path / "state.sqlite", minimum_release=1).accept(
        verify_registry(REGISTRY_BYTES, TRUSTED)
    )
    return registry, key


def _argv(tmp_path: Path, registry: Path, key: Path, *, out: str = "registry.next.json"):
    return [
        "approve",
        "--registry", str(registry),
        "--profile-id", "cpu-tdx-sample-v1",
        "--signing-key-file", str(key),
        "--endpoint", "https://10.0.0.1:8443",
        "--cacert", str(registry),          # unused: _capture is stubbed
        "--hotkey", "5DriftedWorker",
        "--verifier", "/opt/cathedral/bin/cathedral-tdx-verifier",
        "--operator", "ops@cathedral",
        "--reason", "initramfs regenerated by a security update",
        "--approval-log", str(tmp_path / "approvals.jsonl"),
        "--out", str(tmp_path / out),
    ]


def test_approve_signs_a_new_release_carrying_the_drifted_measurement(tmp_path, monkeypatch):
    registry, key = _inputs(tmp_path)
    monkeypatch.setattr(approval, "_capture", lambda *a, **k: _candidate())

    assert approval.main(_argv(tmp_path, registry, key)) == 0

    encoded = (tmp_path / "registry.next.json").read_bytes()
    signed = json.loads(encoded)
    before = json.loads(REGISTRY_BYTES)

    # It is a NEW release, signed, and it verifies under the same trusted key.
    assert signed["release"] > before["release"]
    verify_registry(encoded, TRUSTED)

    # and the drifted measurement is now approved somewhere in it
    assert DRIFTED in json.dumps(signed)


def test_approve_records_who_approved_what_and_why(tmp_path, monkeypatch):
    """The approval log is the audit trail. A recovery that leaves no record of
    which operator re-approved which measurement, from which evidence, is not
    auditable after the fact."""
    registry, key = _inputs(tmp_path)
    monkeypatch.setattr(approval, "_capture", lambda *a, **k: _candidate())
    assert approval.main(_argv(tmp_path, registry, key)) == 0

    lines = (tmp_path / "approvals.jsonl").read_text().strip().splitlines()
    assert len(lines) == 1
    record = json.loads(lines[0])
    assert record["action"] == "measurement_approved"
    assert record["measurement"] == DRIFTED
    assert record["operator"] == "ops@cathedral"
    assert record["reason"] == "initramfs regenerated by a security update"
    assert record["hotkey"] == "5DriftedWorker"
    assert record["tcb_status"] == "UpToDate"
    assert record["registry_digest"].startswith("sha256:")


def test_approve_refuses_to_overwrite_an_existing_output(tmp_path, monkeypatch):
    """Clobbering a signed registry that has already been installed would be
    the worst outcome of a hurried second run."""
    registry, key = _inputs(tmp_path)
    monkeypatch.setattr(approval, "_capture", lambda *a, **k: _candidate())
    (tmp_path / "registry.next.json").write_text("do not clobber me")

    with pytest.raises(FileExistsError):
        approval.main(_argv(tmp_path, registry, key))
    assert (tmp_path / "registry.next.json").read_text() == "do not clobber me"


def test_a_failed_approval_record_rolls_back_the_signed_registry(tmp_path, monkeypatch):
    """The tool unlinks its output if the audit record cannot be written.

    That ordering is the interesting part: a signed registry with no
    corresponding approval entry is exactly the artifact nobody can later
    justify, so it must not survive.
    """
    registry, key = _inputs(tmp_path)
    monkeypatch.setattr(approval, "_capture", lambda *a, **k: _candidate())

    def _explode(*a, **k):
        raise OSError("approval log is on a full disk")

    monkeypatch.setattr(approval, "_secure_append_line", _explode)

    with pytest.raises(OSError, match="approval log is on a full disk"):
        approval.main(_argv(tmp_path, registry, key))
    assert not (tmp_path / "registry.next.json").exists(), (
        "a signed registry survived without its approval record")
